#include<iostream>
using namespace std;
int main()
{
    int month;
    cout<<"enter the month:"<<endl;
    cin>>month;
    switch(month)
    {
        case 12:
        cout<<"it is winter";
        break;
        case 1:
        cout<<"it is winter";
        break;
        case 2:
        cout<<"it is winter";
        break;
        case 3:
        cout<<"it is spring";
        break;
        case 4:
        cout<<"it is spring";
        break;
        case 5:
        cout<<"it is spring";
        break;
        case 6:
        cout<<"it is summer";
        break;
        case 7:
        cout<<"it is summer";
        break;
        case 8:
        cout<<"it is summer";
        break;
        case 9:
        cout<<"it is fall";
        break;
        case 10:
        cout<<"it is fall";
        break;
        case 11:
        cout<<"it is fall";
        break;




    
    }
}